import { useEffect, useState } from "react";
import { api } from "./api.js";

// Multi-language UI texts
const TEXTS = {
  fr: {
    title: "Firasa",
    subtitle: "Moteur d'orientation entrepreneuriale",
    online: "en ligne",
    offline: "hors ligne",
    tagline: "Un auditeur algorithmique, pas un chatbot.",
    taglineSub: "Firasa confronte votre auto-évaluation aux preuves, calcule des scores explicables à portes, et trace une feuille de route ancrée dans l'écosystème tunisien réel.",
    pillar1Title: "Diagnostic adaptatif",
    pillar1Desc: "Collecte ramifiée et classification en 6 stades, avec détection de l'écart perception-réalité.",
    pillar2Title: "Scoring GWLC explicable",
    pillar2Desc: "Combinaison linéaire pondérée à portes non-linéaires — chaque score est traçable au critère près.",
    pillar3Title: "Parcours ancré (RAG)",
    pillar3Desc: "Chaque recommandation cite une institution tunisienne réelle : APII, BFPME, BTS, Startup Act...",
    projectNameLabel: "Nom du projet",
    projectNamePlaceholder: "Ex. AgriSmart Tunisie",
    startAudit: "Démarrer l'audit",
    recentAudits: "Audits récents",
    noRecent: "Aucun audit récent dans ce navigateur.",
    resume: "Reprendre",
    newAuditBtn: "Nouvel audit",
    partialAuditBtn: "Auditer maintenant (données partielles)",
    adaptiveIntake: "Collecte adaptative",
    adaptiveIntakeSub: "Le système choisit chaque question selon vos réponses précédentes — séquence ramifiée, jamais un formulaire figé.",
    validateContinue: "Valider et continuer",
    collected: "collecté",
    perceptionGapTitle: "Écart Perception-Réalité",
    declaredStage: "Stade Déclaré",
    evidenceStage: "Stade Classifié (Objectif)",
    confidence: "Confiance",
    gateLadderTitle: "Échelle de Maturité Diagnostic",
    activeGate: "PORTE ACTIVE",
    scorePanelTitle: "Scores GWLC Explicables",
    scorePanelSub: "Combinaison linéaire à portes. Cliquez sur une ligne pour voir le détail des critères.",
    scoreVector: "Vecteur",
    referenceFramework: "Cadre de référence",
    gateReason: "Règle de Gate active",
    missingData: "Données manquantes pour cette dimension",
    anomaliesTitle: "Alertes d'Incohérence Structurelle",
    anomaliesSub: "Incohérences logiques détectées entre vos différentes réponses par l'auditeur backend.",
    roadmapTitle: "Feuille de route (Mon Parcours)",
    roadmapSub: "Actions prioritaires et opportunités d'accompagnement basées sur votre profil.",
    roadmapChecked: "Terminée",
    assistantTitle: "Assistant Conseil Grounded",
    assistantSub: "Posez des questions sur votre diagnostic. Les réponses sont bridées et sourcées uniquement sur vos résultats et la base de connaissances.",
    askAssistantPlaceholder: "Ex. Quels financements s'offrent à moi à ce stade ?",
    send: "Envoyer",
    groundingContext: "Contexte de grounding utilisé par l'IA",
    sourcesUsed: "Sources citées",
    noSector: "Secteur non spécifié",
    reallocationMsg: "Réallocation automatique appliquée au stade objectif.",
    deltaPrev: "Auparavant",
    deltaCurr: "Actuel",
    deltaChange: "Évolution",
    yes: "Oui",
    no: "Non",
    commaSeparated: "Séparez les tags par des virgules",
    loadByIdLabel: "Charger par ID de projet",
    loadByIdBtn: "Charger",
  },
  ar: {
    title: "فِراسة",
    subtitle: "محرّك التوجيه والمرافقة الريادية",
    online: "متصل",
    offline: "غير متصل",
    tagline: "مُدقّق خوارزمي هيكلي، وليس مجرد مجيب آلي.",
    taglineSub: "يقوم نظام فِراسة بمقارنة تقييمك الذاتي بالأدلة الملموسة، ويحتسب مؤشرات أداء قابلة للتفسير مع قواعد تصفية صارمة، ويخطط مسار عمل مستند إلى مؤسسات النظام الريادي التونسي.",
    pillar1Title: "تشخيص تكيّفي",
    pillar1Desc: "جمع بيانات متفرع وتصنيف عبر 6 مراحل مع كشف الفجوة بين التقييم الذاتي والواقع الأداتي.",
    pillar2Title: "مؤشرات أداء مفسّرة",
    pillar2Desc: "دمج خطي مرجح مدعوم ببوابات غير خطية — كل مؤشر قابل للتتبع والتفكيك لكل معيار تفصيلي.",
    pillar3Title: "مسار موثق ومؤطر",
    pillar3Desc: "كل توصية تستند إلى برامج ومؤسسات تونسية حقيقية: APII ،BFPME ،BTS ،Startup Act...",
    projectNameLabel: "اسم المشروع",
    projectNamePlaceholder: "مثال: ذكاء فلاحي تونس",
    startAudit: "بدء التدقيق والتقييم",
    recentAudits: "عمليات التدقيق الأخيرة",
    noRecent: "لا توجد عمليات تدقيق محفوظة في هذا المتصفح.",
    resume: "استئناف التقييم",
    newAuditBtn: "تدقيق جديد",
    partialAuditBtn: "تدقيق الآن (بيانات جزئية)",
    adaptiveIntake: "جمع البيانات ال