// 5 prebuilt demo profiles for judges: 3 perception-reality gap + 2 anomaly cases.
// Each maps directly to ProfilePatchBody fields (PATCH /api/projects/{pid}).

export const DEMO_SCENARIOS = [
  {
    id: "g1",
    label: "🚀 \"On lève des fonds\"",
    labelAr: "🚀 \"نحن نجمع التمويل\"",
    description: "Déclaré: Fundraising → Diagnostiqué: Idéation (écart critique)",
    descriptionAr: "مُعلَن: تمويل → مُشخَّص: فكرة (فجوة حرجة)",
    tag: "gap",
    fields: {
      demo: true,
      name: "AgriConnect TN",
      sector: "agri-food",
      // Self-assessment: claims financing stage
      declared_stage: 4,
      declared_revenue: false,
      // Passes gate 1 (ideation: problem + segment)
      has_problem_statement: true,
      user_segment_identified: true,
      // Fails gate 2: no customer validation → classified = Ideation
      customer_validation_evidence: false,
      // Large TAM claim without validation → triggers anomaly A1
      estimated_tam_tnd: 8000000,
      competitor_headcount: 3,
      // No legal structure
      legal_form: "None",
      // No revenue model → triggers anomaly A3 (advanced stage, no revenue)
      has_revenue_model: false,
      months_unit_economics: 0,
      // Product still a concept
      mvp_stage: "Concept",
      value_proposition_narrative: "Marketplace B2B connectant producteurs agricoles et acheteurs institutionnels en Tunisie",
      human_dependency: 7,
      repeatable_sales: false,
      sdg_targets: [2, 12],
      // Green: no footprint data (anomaly A7 if green score high enough)
      circular_recycling: false,
    },
  },
  {
    id: "g2",
    label: "⚙️ \"Startup scalable\"",
    labelAr: "⚙️ \"شركة ناشئة قابلة للتوسع\"",
    description: "Déclaré: Croissance → Diagnostiqué: Lancement (dépendance humaine)",
    descriptionAr: "مُعلَن: نمو → مُشخَّص: إطلاق (اعتماد بشري)",
    tag: "gap",
    fields: {
      demo: true,
      name: "HRDigital",
      sector: "digital-saas",
      declared_stage: 6,
      declared_revenue: true,
      // Gates 1-5 all pass → classified = Launch Planning (5)
      has_problem_statement: true,
      user_segment_identified: true,
      customer_validation_evidence: true,
      legal_form: "SARL",
      has_revenue_model: true,
      months_unit_economics: 8,
      mvp_stage: "Prototype",
      // Gate 6 fails: human_dependency > 7 → classified = 5 not 6
      human_dependency: 9,
      repeatable_sales: false,
      // Low costs but high human dependency → triggers anomaly A2
      monthly_overhead: 600,
      equipment_cost: 200,
      // High innovation claims + no IP → triggers anomaly A6
      geo_novelty: "Global",
      tech_stack: ["Python", "React", "SaaS", "Cloud"],
      ip_status: "None",
      estimated_tam_tnd: 3000000,
      competitor_headcount: 5,
      value_proposition_narrative: "Plateforme SaaS RH pour PME tunisiennes — automatisation paie et recrutement",
    },
  },
  {
    id: "g3",
    label: "📱 \"MVP prêt, on lance\"",
    labelAr: "📱 \"MVP جاهز، سنطلق\"",
    description: "Déclaré: Lancement → Diagnostiqué: Validation marché (sans forme juridique)",
    descriptionAr: "مُعلَن: إطلاق → مُشخَّص: التحقق من السوق (لا شكل قانوني)",
    tag: "gap",
    fields: {
      demo: true,
      name: "EduPro Tunisia",
      sector: "digital-saas",
      declared_stage: 5,
      declared_revenue: false,
      // Gates 1-2 pass
      has_problem_statement: true,
      user_segment_identified: true,
      customer_validation_evidence: true,
      estimated_tam_tnd: 2500000,
      competitor_headcount: 8,
      // Gate 3 fails: no registered legal form → classified = Market Validation (2)
      legal_form: "None",
      // Product still a concept → triggers anomaly A4 (market signal but no product)
      mvp_stage: "Concept",
      value_proposition_narrative: "Application e-learning gamifiée pour lycéens tunisiens avec suivi personnalisé",
      has_revenue_model: true,
      months_unit_economics: 1,
      human_dependency: 4,
      repeatable_sales: false,
      geo_novelty: "Tunisian First-Mover",
      tech_stack: ["React Native", "Python"],
      ip_status: "None",
    },
  },
  {
    id: "a1",
    label: "🌿 \"Leader du Green\"",
    labelAr: "🌿 \"رائد في المجال الأخضر\"",
    description: "Claims ODD verts sans données d'empreinte mesurées",
    descriptionAr: "يدّعي أهداف بيئية دون بيانات بصمة مقاسة",
    tag: "anomaly",
    fields: {
      demo: true,
      name: "EcoHarvest",
      sector: "agri-food",
      declared_stage: 3,
      declared_revenue: true,
      has_problem_statement: true,
      user_segment_identified: true,
      customer_validation_evidence: true,
      estimated_tam_tnd: 4000000,
      competitor_headcount: 2,
      legal_form: "SARL",
      has_revenue_model: false,
      months_unit_economics: 0,
      mvp_stage: "Mockup",
      value_proposition_narrative: "Circuit court alimentaire connectant producteurs bio et consommateurs urbains",
      human_dependency: 6,
      repeatable_sales: false,
      // Many SDG claims but no footprint data → triggers anomaly A7 (green-washing)
      sdg_targets: [2, 12, 13, 15],
      circular_recycling: false,
      // footprint_category intentionally omitted (null) — the trigger for A7
      geo_novelty: "Tunisian First-Mover",
      tech_stack: ["Mobile", "API"],
      ip_status: "None",
    },
  },
  {
    id: "a2",
    label: "🔬 \"Deep Tech Global\"",
    labelAr: "🔬 \"تقنية عميقة عالمية\"",
    description: "Innovation élevée sans IP + sous-estimation de stade",
    descriptionAr: "ابتكار مرتفع بلا ملكية فكرية + تقليل للمرحلة",
    tag: "anomaly",
    fields: {
      demo: true,
      name: "DeepTech Tunis",
      sector: "digital-saas",
      declared_stage: 4,
      declared_revenue: true,
      // Gates 1-5 pass → classified = Launch Planning (5) > declared (4) = UNDERESTIMATION
      has_problem_statement: true,
      user_segment_identified: true,
      customer_validation_evidence: true,
      estimated_tam_tnd: 12000000,
      competitor_headcount: 4,
      legal_form: "SUARL",
      has_revenue_model: true,
      months_unit_economics: 6,
      mvp_stage: "Prototype",
      value_proposition_narrative: "Plateforme IA d'analyse prédictive pour optimisation de chaînes logistiques MENA",
      human_dependency: 5,
      repeatable_sales: false,
      monthly_overhead: 900,
      equipment_cost: 400,
      // High innovation claims without IP → triggers anomaly A6
      geo_novelty: "Global",
      tech_stack: ["AI/ML", "Python", "Cloud", "Blockchain"],
      ip_status: "None",
      sdg_targets: [9, 17],
      circular_recycling: false,
    },
  },
];
